### ISSUE TITLE
TypeError when using PyDM: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/adl2pydm#60]
**Describe the bug**

Receiving this exception when starting PyDM 1.11.1 today:

```python
[2021-10-22 13:41:24,332] [INFO    ] - file not found: stylesheet.qss
[2021-10-22 13:41:24,332] [INFO    ] - writing screen file: None
Traceback (most recent call last):
  File "/home/prjemian/.conda/envs/bluesky_2021_2/lib/python3.8/site-packages/pydm/widgets/related_display_button.py", line 348, in open_display
    load_file(fname, macros=macros, target=screen_target)
  File "/home/prjemian/.conda/envs/bluesky_2021_2/lib/python3.8/site-packages/pydm/display.py", line 60, in load_file
    app.new_pydm_process(file, macros=macros, command_line_args=args)
  File "/home/prjemian/.conda/envs/bluesky_2021_2/lib/python3.8/site-packages/pydm/application.py", line 159, in new_pydm_process
    ui_file = os.path.expanduser(os.path.expandvars(ui_file))
  File "/home/prjemian/.conda/envs/bluesky_2021_2/lib/python3.8/posixpath.py", line 284, in expandvars
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**To Reproduce**

Start [docker xxx IOC](https://github.com/prjemian/epics-docker/blob/main/v1.1/n5_custom_synApps/start_xxx.sh) on linux:

```bash
start_xxx.sh gp
```

Copy `start_MEDM_gp` bash script to `start_PyDM_gp` and modify to read:

```bash
#!/bin/bash

# Requires PyDM and adl2pydm python packages

# export EPICS_APP=`dirname ${BASH_SOURCE:-$0}`
export EPICS_APP=/tmp/docker_ioc/iocgp/xxx-R6-2
export EPICS_APP_ADL_DIR=${EPICS_APP}/xxxApp/op/adl
export DEFAULT_UI_FILE=${DEFAULT_UI_FILE:-xxx.adl}

export EPICS_DISPLAY_PATH=/tmp/docker_ioc/iocgp/xxx-R6-2/xxxApp/op/adl
export EPICS_DISPLAY_PATH+=:/tmp/docker_ioc/custom-synapps-6.2/screens/adl
export PYDM_DISPLAYS_PATH="${EPICS_DISPLAY_PATH}"

if [ -z "${MEDM_EXEC_LIST}" ] 
then
    export MEDM_EXEC_LIST='Probe;probe &P &'
fi

#export EPICS_CA_ADDR_LIST="164.54.53.126"

# This should agree with the environment variable set by the ioc
# see 'putenv "EPICS_CA_MAX_ARRAY_BYTES=64008"' in iocBoot/ioc<target>/st.cmd
export EPICS_CA_MAX_ARRAY_BYTES=64008

export START_PUTRECORDER=${EPICS_APP}/start_putrecorder
export MACROS_PY=${EPICS_APP_ADL_DIR}/../python/macros.py
export EDITOR=nedit

export OPTIONS=
export OPTIONS+=" --hide-nav-bar"  # Start with navigation bar hidden
export OPTIONS+=" --hide-menu-bar"  # Start with menu bar hidden
export OPTIONS+=" --hide-status-bar"  # Start with status bar hidden

pydm ${OPTIONS} ${1:-${DEFAULT_UI_FILE}} $* &
```

Run `start_PyDM_gp` and see main screen:
![xxx main screen in PyDM](https://user-images.githubusercontent.com/2279984/138507605-c06d3694-47fa-48c8-906b-8061a2342c3c.png)

Click on any of the pop-up menu items and error (above) appears.

**Expected behavior**
New screen should appear.

**Comment by prjemian** [comment]
Tested for this by first converting all necessary MEDM files to PyDM and starting with only PyDM's `.ui` files (ignoring any extra graphics files needed by some screens).

```bash
export PYDM_DISPLAYS_PATH=/tmp/screens/
mkdir ${PYDM_DISPLAYS_PATH}

adl2pydm -d ${PYDM_DISPLAYS_PATH} /tmp/docker_ioc/custom-synapps-6.2/screens/adl/*.adl
adl2pydm -d ${PYDM_DISPLAYS_PATH} /tmp/docker_ioc/iocgp/xxx-R6-2/xxxApp/op/adl/*.adl

pydm --hide-{nav,menu,status}-bar xxx.ui &
```

This is a problem in the PyDM application directly, in `display.py`, line 57:

```python
    if target == ScreenTarget.NEW_PROCESS:
        # Invoke PyDM to open a new process here.
        app = QApplication.instance()
        app.new_pydm_process(file, macros=macros, command_line_args=args)
        return None
```

A new process is requested for the new screen.  The code above bypasses the checks for `.adl` file extension and the call to `app.new_pydm_process(file,...` does not handle `.adl` files.  This is a bug in PyDM.

**Comment by prjemian** [comment]
Can close this issue as `wontfix` here once an issue is filed with [PyDM's issue tracker](https://github.com/slaclab/pydm/issues).
